### PR TITLE
Hgfffy

### PR DESCRIPTION
**Pull request by hgfffy**

### CODE REVIEW

**Comment by MedovTimur** [comment]
Hi!
Try fixing the CI :)

**Comment by hgfffy** [comment]
> Hi! Try fixing the CI :)


I've submitted a new PR to solve the problem, but the same error appears during testing in CI, and I can't resolve it. However, after deploying it in https://idea.gear-tech.io/, the functionality works without any issues.
pr:https://github.com/hgfffy/hgfffy-gear-academy/pull/5
new id:0xf0656b150618fb84b3ac2dab1049813a349a53a4d3c7e4e29f51bc65bad4b593

**Comment by MedovTimur** [comment]
Hi
you had a formatting problem, a simple `cargo fmt --all` command would have solved it, why did you delete all your code?)

**Comment by hgfffy** [comment]
> Hi you had a formatting problem, a simple `cargo fmt --all` command would have solved it, why did you delete all your code?)
 
 new pr https://github.com/hgfffy/hgfffy-gear-academy/pull/5

I didn't know how to fix it before, and after making some random changes, I ended up deleting the code. Now, my new PR has solved the problem, but there is a new issue during testing.

**Pull request closed without merging**
